# -*- coding: utf-8 -*-
"""KDM_LAB3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19D4ieWpVfe6L73xWV0c9jL71_PY_qVZP
"""

import nltk
nltk.download('all')
from nltk.corpus import wordnet

"""WordNet task"""

print('Hyponyms ->')
print(wordnet.synset('calendar.n.01').hyponyms())
print('\n')
print('Hypernyms ->')
print(wordnet.synset('solar_calendar.n.01').hypernyms())
print('\n')
print('Holonyms ->')
print(wordnet.synset('kitchen.n.01').part_holonyms())
print('\n')
print('Meronyms -> ')
print(wordnet.synset('dwelling.n.01').part_meronyms())
print('\n')
print('Entailment -> ')
print(wordnet.synset('look.v.01').entailments())